before:
  hooks:
    - go mod tidy
builds:
  -
    id: headless
    binary: netclient
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_mips_hardfloat
      - linux_mips_softfloat
      - linux_mipsle_softfloat
      - linux_mipsle_hardfloat
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_386

archives:
  - format: binary
    name_template: >-
      {{ .Binary }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64{{ else if eq .Arch "386" }}386{{ else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- with .Mips }}-{{ . }}{{ end }}
      {{- if eq .Os "windows" }}.exe{{ end }}
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      arm: arm
      amd64: amd64
      386: 386
      arm64: arm64
    allow_different_binary_count: true

release:
  prerelease: false
