name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:
    release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gravitl/netclient
          ref: develop
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
      - name: Setup git
        run: |
          git config --global user.name "Sayan Mallick"
          git config --global user.email "snyxmk@gmail.com"
      - name: Create Release Branch
        run: |
          git switch -c release-${{ inputs.version }}
      - name: Fix go mod
        run: |
          go get github.com/gravitl/netmaker@${{ inputs.version }}
          go mod tidy
          git commit -am 'update go mod for release'
      - name: Update Release Branch
        run: |
          git tag -f ${{ inputs.version }}
          git push origin release-${{ inputs.version }}
          git push origin ${{ inputs.version }}

    release-assets:
      needs: release-branch
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: gravitl/netclient
            ref: release-${{ inputs.version }}
            fetch-depth: 0
        - name: Get Tags
          run: |
            git fetch --force --tags
        - name: Setup go
          uses: actions/setup-go@v5
          with:
            go-version: 1.23
        - name: GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            args: release --clean --release-notes release.md
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
